### ISSUE TITLE
HSSSS 2.0.0 Beta 1 SUPPORT?

### ISSUE THREAD

**Issue by shivdbz2010** [arthurOmanko/HSSSSforVR#1]
HSSSS 2.0.0 Beta 1?

**Comment by arthurOmanko** [comment]
> HSSSS 2.0.0 Beta 1?

hi.
Now I am in another country for a while (not residential country) so cant use VR for a while.
I noticed HSSSS 2.0.0 released now and am being excited.
I'll update HSSSSforVR for 2.0.0. but for a while cant.
I'll prepare in very near future by some means and release new one!

**Comment by arthurOmanko** [comment]
> HSSSS 2.0.0 Beta 1?

Today I updated HSSSSforVR for HSSSS ver 2.0.0_beta2.
tks for your interest.

**Comment by arthurOmanko** [comment]
tks.
